Repository BHoM/XML_Toolkit, pull requests merged in 2019-09, with the labels that each got.

#341 Removed unessesary filePath
  XML_Engine/Query/XMLFilePath.cs
  XML_Engine/XML_Engine.csproj
Labels: size:XS

#345 Update variable name usage
  XML_Adapter/Serialise/Opening.cs
Labels: type:compliance

#350 Update references for compliance
  XML_Adapter/XML_Adapter.csproj
  XML_Engine/XML_Engine.csproj
Labels: type:compliance

#347 Update references to Level from Architecture to Geometry.SettingOut
  XML_Adapter/CRUD/Read.cs
  XML_Adapter/Serialise/Level.cs
  XML_Adapter/Serialise/Panel.cs
  XML_Engine/Convert/Architecture_oM/Level.cs
  XML_Engine/Create/DocumentBuilder.cs
  XML_oM/DocumentBuilder.cs
  XML_oM/XML_oM.csproj
Labels: severity:low, status:do-not-merge, type:compliance

#353 Update file assembly version and set copy local to false for BHoM dependencies
  XML_Adapter/Properties/AssemblyInfo.cs
  XML_Adapter/XML_Adapter.csproj
  XML_Engine/Properties/AssemblyInfo.cs
  XML_Engine/XML_Engine.csproj
  XML_oM/Properties/AssemblyInfo.cs
  XML_oM/XML_oM.csproj
  docs/CODEOWNERS
Labels: type:compliance

#354 Fix Construction push bug
  XML_Engine/Convert/Environment_oM/Construction.cs
Labels: type:bug
