Repository BHoM/XML_Toolkit, pull requests merged in 2019-11, with the labels that each got.

#371 XML_Toolkit Push warning for Tilt
  XML_Engine/Convert/Environment_oM/Panel.cs
Labels: type:documentation, type:feature

#373 Resolve compiler warnings
  XML_oM/GBXML/Campus/Building.cs
  XML_oM/GBXML/Campus/BuildingStorey.cs
  XML_oM/GBXML/Campus/Campus.cs
  XML_oM/GBXML/Campus/Location.cs
  XML_oM/GBXML/Campus/Opening.cs
  XML_oM/GBXML/Campus/Space.cs
  XML_oM/GBXML/Campus/Surface.cs
  XML_oM/GBXML/Construction/Construction.cs
  XML_oM/GBXML/Materials/Material.cs
  XML_oM/GBXML/Window/Gap.cs
  XML_oM/GBXML/Window/Glaze.cs
  XML_oM/GBXML/Window/WindowType.cs
  XML_oM/GBXML/Zone/Zone.cs
  XML_oM/XML_oM.csproj
Labels: size:XS, type:documentation

#374 Add input parameters to clean polyline method
  XML_Engine/Convert/Geometry_oM/Polyline.cs
Labels: size:XS, type:feature
