Repository BHoM/XML_Toolkit, pull requests merged in 2020-04, with the labels that each got.

#437 Change Level from Float to Double
  XML_oM/GBXML/Campus/BuildingStorey.cs
Labels: type:compliance

#448 Change normal away from space calculation to use first connected space only
  XML_Adapter/Convert/GBXML/Environment/Panel.cs
Labels: type:bug

#450 Removing Deprecated Geometry methods
  XML_Adapter/Convert/GBXML/Environment/Panel.cs
Labels: type:external-api-changes
