Repository BHoM/XML_Toolkit, pull requests merged in 2020-03, with the labels that each got.

#428 Add AngleTolerance parameter to XMLSettings
  XML_Adapter/Serialise/Panel.cs
  XML_Engine/Convert/Environment/Panel.cs
  XML_oM/XMLSettings.cs
Labels: type:feature

#430 Update CI Files
  .ci/check-all-depandants.yml
  .ci/check-core.yml
  .ci/check-installer.yml
  .ci/run-compliance-tests.yml
Labels: type:compliance

#433 Null item protection
  XML_Adapter/Serialise/Opening.cs
Labels: type:bug
