Repository BHoM/XML_Toolkit, pull requests merged in 2020-05, with the labels that each got.

#457 Update ReadMe
  README.md
Labels: type:documentation

#460 Remove SolarPanel
  XML_Adapter/Convert/GBXML/Environment/ElementType.cs
Labels: type:bug

#464 Change KML polygon conversion to handle triangular mesh faces
  XML_Adapter/Convert/KML/Mesh.cs
Labels: severity:low, type:bug

#467 Update to oM Changes
  XML_Adapter/Convert/GBXML/Environment/Building.cs
Labels: type:external-api-changes

#468 Using Hole as ElementType
  XML_Adapter/Convert/GBXML/Environment/ElementType.cs
Labels: type:feature

#472 Add space perimeter to space on pull
  XML_Adapter/CRUD/GBXML/ReadGBXML.cs
Labels: type:feature

#474 Remove legacy code
  XML_Engine/Create/XMLSettings.cs
Labels: type:compliance
